packages:
  - apps/*

allowBuilds:
  '@parcel/watcher': true
  lightningcss: true

minimumReleaseAgeExclude:
  - '@vitejs/plugin-react@6.1.2'
  - '@formatjs/icu-messageformat-parser@3.5.21'
  - '@formatjs/intl@6.1.3'
  - intl-messageformat@12.1.3
  - react-intl@12.1.4
  - vite@8.3.3
