/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Oauth2ContinueRouteImport } from './routes/oauth2.continue'
import { Route as LoginChallengeRouteImport } from './routes/login.challenge'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2ContinueRoute = Oauth2ContinueRouteImport.update({
  id: '/oauth2/continue',
  path: '/oauth2/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginChallengeRoute = LoginChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => LoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRouteWithChildren
  '/login/challenge': typeof LoginChallengeRoute
  '/oauth2/continue': typeof Oauth2ContinueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRouteWithChildren
  '/login/challenge': typeof LoginChallengeRoute
  '/oauth2/continue': typeof Oauth2ContinueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRouteWithChildren
  '/login/challenge': typeof LoginChallengeRoute
  '/oauth2/continue': typeof Oauth2ContinueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/consent' | '/login' | '/login/challenge' | '/oauth2/continue'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consent' | '/login' | '/login/challenge' | '/oauth2/continue'
  id:
    | '__root__'
    | '/'
    | '/consent'
    | '/login'
    | '/login/challenge'
    | '/oauth2/continue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRouteWithChildren
  Oauth2ContinueRoute: typeof Oauth2ContinueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/continue': {
      id: '/oauth2/continue'
      path: '/oauth2/continue'
      fullPath: '/oauth2/continue'
      preLoaderRoute: typeof Oauth2ContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/challenge': {
      id: '/login/challenge'
      path: '/challenge'
      fullPath: '/login/challenge'
      preLoaderRoute: typeof LoginChallengeRouteImport
      parentRoute: typeof LoginRoute
    }
  }
}

interface LoginRouteChildren {
  LoginChallengeRoute: typeof LoginChallengeRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginChallengeRoute: LoginChallengeRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRouteWithChildren,
  Oauth2ContinueRoute: Oauth2ContinueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
