/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoginChallengeRouteImport } from './routes/login.challenge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginChallengeRoute = LoginChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => LoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRouteWithChildren
  '/login/challenge': typeof LoginChallengeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRouteWithChildren
  '/login/challenge': typeof LoginChallengeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRouteWithChildren
  '/login/challenge': typeof LoginChallengeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consent' | '/install' | '/login' | '/login/challenge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consent' | '/install' | '/login' | '/login/challenge'
  id: '__root__' | '/' | '/consent' | '/install' | '/login' | '/login/challenge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/challenge': {
      id: '/login/challenge'
      path: '/challenge'
      fullPath: '/login/challenge'
      preLoaderRoute: typeof LoginChallengeRouteImport
      parentRoute: typeof LoginRoute
    }
  }
}

interface LoginRouteChildren {
  LoginChallengeRoute: typeof LoginChallengeRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginChallengeRoute: LoginChallengeRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
