/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as AppearanceRouteImport } from './routes/appearance'
import { Route as AuthorizationErrorRouteImport } from './routes/authorization-error'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountIdentifiersRouteImport } from './routes/account/identifiers'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountSessionsRouteImport } from './routes/account/sessions'
import { Route as HealthLiveRouteImport } from './routes/health.live'
import { Route as HealthReadyRouteImport } from './routes/health.ready'
import { Route as LoginChallengeRouteImport } from './routes/login.challenge'
import { Route as AccountMfaSetupRouteImport } from './routes/account/mfa/setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppearanceRoute = AppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizationErrorRoute = AuthorizationErrorRouteImport.update({
  id: '/authorization-error',
  path: '/authorization-error',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountIdentifiersRoute = AccountIdentifiersRouteImport.update({
  id: '/identifiers',
  path: '/identifiers',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSessionsRoute = AccountSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AccountRouteRoute,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginChallengeRoute = LoginChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => LoginRoute,
} as any)
const AccountMfaSetupRoute = AccountMfaSetupRouteImport.update({
  id: '/mfa/setup',
  path: '/mfa/setup',
  getParentRoute: () => AccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/appearance': typeof AppearanceRoute
  '/authorization-error': typeof AuthorizationErrorRoute
  '/callback': typeof CallbackRoute
  '/consent': typeof ConsentRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRouteWithChildren
  '/account/identifiers': typeof AccountIdentifiersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/login/challenge': typeof LoginChallengeRoute
  '/account/': typeof AccountIndexRoute
  '/account/mfa/setup': typeof AccountMfaSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appearance': typeof AppearanceRoute
  '/authorization-error': typeof AuthorizationErrorRoute
  '/callback': typeof CallbackRoute
  '/consent': typeof ConsentRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRouteWithChildren
  '/account/identifiers': typeof AccountIdentifiersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/login/challenge': typeof LoginChallengeRoute
  '/account': typeof AccountIndexRoute
  '/account/mfa/setup': typeof AccountMfaSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/appearance': typeof AppearanceRoute
  '/authorization-error': typeof AuthorizationErrorRoute
  '/callback': typeof CallbackRoute
  '/consent': typeof ConsentRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRouteWithChildren
  '/account/identifiers': typeof AccountIdentifiersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/login/challenge': typeof LoginChallengeRoute
  '/account/': typeof AccountIndexRoute
  '/account/mfa/setup': typeof AccountMfaSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/appearance'
    | '/authorization-error'
    | '/callback'
    | '/consent'
    | '/install'
    | '/login'
    | '/account/identifiers'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/health/live'
    | '/health/ready'
    | '/login/challenge'
    | '/account/'
    | '/account/mfa/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appearance'
    | '/authorization-error'
    | '/callback'
    | '/consent'
    | '/install'
    | '/login'
    | '/account/identifiers'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/health/live'
    | '/health/ready'
    | '/login/challenge'
    | '/account'
    | '/account/mfa/setup'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/appearance'
    | '/authorization-error'
    | '/callback'
    | '/consent'
    | '/install'
    | '/login'
    | '/account/identifiers'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/health/live'
    | '/health/ready'
    | '/login/challenge'
    | '/account/'
    | '/account/mfa/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AppearanceRoute: typeof AppearanceRoute
  AuthorizationErrorRoute: typeof AuthorizationErrorRoute
  CallbackRoute: typeof CallbackRoute
  ConsentRoute: typeof ConsentRoute
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRouteWithChildren
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appearance': {
      id: '/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorization-error': {
      id: '/authorization-error'
      path: '/authorization-error'
      fullPath: '/authorization-error'
      preLoaderRoute: typeof AuthorizationErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/identifiers': {
      id: '/account/identifiers'
      path: '/identifiers'
      fullPath: '/account/identifiers'
      preLoaderRoute: typeof AccountIdentifiersRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/sessions': {
      id: '/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AccountSessionsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/challenge': {
      id: '/login/challenge'
      path: '/challenge'
      fullPath: '/login/challenge'
      preLoaderRoute: typeof LoginChallengeRouteImport
      parentRoute: typeof LoginRoute
    }
    '/account/mfa/setup': {
      id: '/account/mfa/setup'
      path: '/mfa/setup'
      fullPath: '/account/mfa/setup'
      preLoaderRoute: typeof AccountMfaSetupRouteImport
      parentRoute: typeof AccountRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountIdentifiersRoute: typeof AccountIdentifiersRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSessionsRoute: typeof AccountSessionsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountMfaSetupRoute: typeof AccountMfaSetupRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountIdentifiersRoute: AccountIdentifiersRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSessionsRoute: AccountSessionsRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountMfaSetupRoute: AccountMfaSetupRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface LoginRouteChildren {
  LoginChallengeRoute: typeof LoginChallengeRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginChallengeRoute: LoginChallengeRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AppearanceRoute: AppearanceRoute,
  AuthorizationErrorRoute: AuthorizationErrorRoute,
  CallbackRoute: CallbackRoute,
  ConsentRoute: ConsentRoute,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRouteWithChildren,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
