//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "client_scope")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_client_scope_client_scope")]
    pub client_id: i64,
    #[sea_orm(unique_key = "idx_client_scope_client_scope")]
    pub scope_id: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::client::Entity",
        from = "Column::ClientId",
        to = "super::client::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Client,
    #[sea_orm(
        belongs_to = "super::scope::Entity",
        from = "Column::ScopeId",
        to = "super::scope::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Scope,
}

impl Related<super::client::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Client.def()
    }
}

impl Related<super::scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scope.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
