//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "client_open_id_connect")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub client_id: i64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub post_logout_redirect_uris: Option<Json>,
    pub frontchannel_logout_uri: Option<String>,
    pub frontchannel_logout_session_required: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub response_types: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub grant_types: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub contacts: Option<Json>,
    pub logo_uri: Option<String>,
    pub client_uri: Option<String>,
    pub policy_uri: Option<String>,
    pub tos_uri: Option<String>,
    pub sector_identifier_uri: Option<String>,
    pub subject_type: Option<String>,
    pub id_token_signed_response_alg: Option<String>,
    pub id_token_encrypted_response_alg: Option<String>,
    pub id_token_encrypted_response_enc: Option<String>,
    pub userinfo_signed_response_alg: Option<String>,
    pub userinfo_encrypted_response_alg: Option<String>,
    pub userinfo_encrypted_response_enc: Option<String>,
    pub request_object_signing_alg: Option<String>,
    pub request_object_encryption_alg: Option<String>,
    pub request_object_encryption_enc: Option<String>,
    pub token_endpoint_auth_method: Option<String>,
    pub token_endpoint_auth_signing_alg: Option<String>,
    pub default_max_age: Option<i32>,
    pub require_auth_time: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub default_acr_values: Option<Json>,
    pub initiate_login_uri: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub request_uris: Option<Json>,
    #[sea_orm(column_type = "JsonBinary")]
    pub settings: Json,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::client::Entity",
        from = "Column::ClientId",
        to = "super::client::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Client,
}

impl Related<super::client::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Client.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
