//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "client")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub oid: Uuid,
    pub protocol: String,
    pub name: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub names: Option<Json>,
    pub description: Option<String>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::client_open_id_connect::Entity")]
    ClientOpenIdConnect,
    #[sea_orm(has_many = "super::client_open_id_connect_credential::Entity")]
    ClientOpenIdConnectCredential,
    #[sea_orm(has_many = "super::client_authorization::Entity")]
    ClientAuthorization,
    #[sea_orm(has_many = "super::client_scope::Entity")]
    ClientScope,
    #[sea_orm(has_many = "super::client_platform::Entity")]
    ClientPlatform,
    #[sea_orm(has_many = "super::login::Entity")]
    Login,
}

impl Related<super::client_open_id_connect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientOpenIdConnect.def()
    }
}

impl Related<super::client_open_id_connect_credential::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientOpenIdConnectCredential.def()
    }
}

impl Related<super::client_authorization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientAuthorization.def()
    }
}

impl Related<super::client_scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScope.def()
    }
}

impl Related<super::client_platform::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientPlatform.def()
    }
}

impl Related<super::login::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Login.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
