//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod client;
pub mod client_open_id_connect;
pub mod client_open_id_connect_credential;
pub mod client_request;
pub mod key;
pub mod login;
pub mod session;
pub mod setting;
pub mod user;
pub mod user_credential;
