//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::client::Entity as Client;
pub use super::client_open_id_connect::Entity as ClientOpenIdConnect;
pub use super::client_open_id_connect_credential::Entity as ClientOpenIdConnectCredential;
pub use super::client_request::Entity as ClientRequest;
pub use super::client_scope::Entity as ClientScope;
pub use super::key::Entity as Key;
pub use super::login::Entity as Login;
pub use super::scope::Entity as Scope;
pub use super::session::Entity as Session;
pub use super::setting::Entity as Setting;
pub use super::user::Entity as User;
pub use super::user_credential::Entity as UserCredential;
