//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "scope")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub oid: Uuid,
    #[sea_orm(unique_key = "idx_scope_protocol_name")]
    pub protocol: String,
    #[sea_orm(unique_key = "idx_scope_protocol_name")]
    pub name: String,
    pub display_name: String,
    pub description: String,
    pub built_in: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::client_scope::Entity")]
    ClientScope,
}

impl Related<super::client_scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScope.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
