services:
  login:
    environment:
      IDENTITY_CLIENT_CREDENTIALS_FILE: /var/lib/identity-login/client.json
    volumes:
      - identity_login_credentials:/var/lib/identity-login

volumes:
  identity_login_credentials:
