apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity.fullname" . }}-server
  labels:
    {{- include "identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.identity.service.type }}
  selector:
    {{- include "identity.serverSelectorLabels" . | nindent 4 }}
  ports:
    - name: {{ ternary "https" "http" .Values.identity.tls.enabled }}
      appProtocol: {{ ternary "https" "http" .Values.identity.tls.enabled }}
      port: {{ .Values.identity.service.publicPort }}
      targetPort: {{ ternary "https" "http" .Values.identity.tls.enabled }}
    - name: {{ ternary "graphql-https" "graphql-http" .Values.identity.tls.enabled }}
      appProtocol: {{ ternary "https" "http" .Values.identity.tls.enabled }}
      port: {{ .Values.identity.service.graphqlPort }}
      targetPort: {{ ternary "graphql-https" "graphql-http" .Values.identity.tls.enabled }}
    - name: health
      appProtocol: http
      port: {{ .Values.identity.service.healthPort }}
      targetPort: health
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity.fullname" . }}-server-internal
  labels:
    {{- include "identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    {{- include "identity.serverSelectorLabels" . | nindent 4 }}
  ports:
    - name: {{ ternary "internal-https" "internal-http" .Values.identity.tls.enabled }}
      appProtocol: {{ ternary "https" "http" .Values.identity.tls.enabled }}
      port: {{ .Values.identity.service.internalPort }}
      targetPort: {{ ternary "internal-https" "internal-http" .Values.identity.tls.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity.fullname" . }}-login
  labels:
    {{- include "identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: login
spec:
  type: {{ .Values.login.service.type }}
  selector:
    {{- include "identity.loginSelectorLabels" . | nindent 4 }}
  ports:
    - name: {{ ternary "https" "http" .Values.login.tls.enabled }}
      appProtocol: {{ ternary "https" "http" .Values.login.tls.enabled }}
      port: {{ .Values.login.service.port }}
      targetPort: {{ ternary "https" "http" .Values.login.tls.enabled }}
