{{- if .Values.identity.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity.identityServiceAccountName" . }}
  labels:
    {{- include "identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
  {{- with .Values.identity.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- if and .Values.identity.serviceAccount.create .Values.login.serviceAccount.create }}
---
{{- end }}
{{- if .Values.login.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity.loginServiceAccountName" . }}
  labels:
    {{- include "identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: login
  {{- with .Values.login.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
