apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity.fullname" . }}-identity
  labels:
    {{- include "identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
spec:
  type: {{ .Values.identity.service.type }}
  selector:
    {{- include "identity.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ ternary "https" "http" .Values.identity.tls.enabled }}
      appProtocol: {{ ternary "https" "http" .Values.identity.tls.enabled }}
      port: {{ .Values.identity.service.publicPort }}
      targetPort: {{ ternary "https" "http" .Values.identity.tls.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity.fullname" . }}-identity-internal
  labels:
    {{- include "identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
spec:
  type: ClusterIP
  selector:
    {{- include "identity.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ ternary "internal-https" "internal-http" .Values.identity.tls.enabled }}
      appProtocol: {{ ternary "https" "http" .Values.identity.tls.enabled }}
      port: {{ .Values.identity.service.internalPort }}
      targetPort: {{ ternary "internal-https" "internal-http" .Values.identity.tls.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity.fullname" . }}-login
  labels:
    {{- include "identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: login
spec:
  type: {{ .Values.login.service.type }}
  selector:
    {{- include "identity.loginSelectorLabels" . | nindent 4 }}
  ports:
    - name: {{ ternary "https" "http" .Values.login.tls.enabled }}
      appProtocol: {{ ternary "https" "http" .Values.login.tls.enabled }}
      port: {{ .Values.login.service.port }}
      targetPort: {{ ternary "https" "http" .Values.login.tls.enabled }}
