apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-login
spec:
  template:
    spec:
      containers:
        - name: login
          env:
            - name: IDENTITY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: identity-login-client
                  key: client-id
            - name: IDENTITY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: identity-login-client
                  key: client-secret
            - name: IDENTITY_PUBLIC_APP_URL
              value: https://account.example.com
